rent_Montreal:
  config_file: "/home/mdakk072/projects/coreScraperProject/kijijiCarScraper/config/rent_Montreal.yaml"
  interval: 240  # 4 hours in minutes

rent_Levis:
  config_file: "/home/mdakk072/projects/coreScraperProject/kijijiCarScraper/config/rent_Levis.yaml"
  interval: 480  # 8 hours in minutes

rent_Ottawa:
  config_file: "/home/mdakk072/projects/coreScraperProject/kijijiCarScraper/config/rent_Ottawa.yaml"
  interval: 360  # 6 hours in minutes
